site:
  title: Stargate documentation
  url: /docs/

content:
  sources:
    - url: ../
      start_path: docs
      branches: HEAD

ui:
  bundle:
    url: https://github.com/ianjevans/antora-ui-datastax/releases/download/v0.1/ui-bundle.zip
  supplemental_files: ./supplemental-ui
